[FIX] account_invoice_refund_link: Fix integration tests
Creating partners in integration environment raises this error:

    IntegrityError: null value in column "sale_warn" violates not-null constraint

Moving to post install mode to avoid such errors.